### ISSUE TITLE
TypeError: Cannot read property 'isAnonymous' of undefined

### ISSUE THREAD

**Issue by tamuratak** [lezer-parser/lezer#46]
When I execute a parser generated from the following grammar, `TypeError: Cannot read property 'isAnonymous' of undefined` is thrown.

```
lezer-generator: 0.13.2
lezer: 0.13.1
```

Repository: https://github.com/tamuratak/lezer-yacc/tree/9cffdc94b23d5281fd91d9be96567ce7336db73c

Steps:
1. `npm i`
1. `npm run build`
1. `node bin/tree.js sample/t.y`

```
TypeError: Cannot read property 'isAnonymous' of undefined
    at /Users/tamura/src/github/lezer-yacc/node_modules/lezer-tree/dist/tree.cjs:717:46
    at Array.some (<anonymous>)
    at hasChild (/Users/tamura/src/github/lezer-yacc/node_modules/lezer-tree/dist/tree.cjs:717:26)
    at TreeNode.nextChild (/Users/tamura/src/github/lezer-yacc/node_modules/lezer-tree/dist/tree.cjs:385:61)
    at TreeNode.get firstChild [as firstChild] (/Users/tamura/src/github/lezer-yacc/node_modules/lezer-tree/dist/tree.cjs:398:36)
    at makeTree (/Users/tamura/src/github/lezer-yacc/out/src/bin/tree.js:17:22)
    at makeTree (/Users/tamura/src/github/lezer-yacc/out/src/bin/tree.js:26:18)
    at Object.<anonymous> (/Users/tamura/src/github/lezer-yacc/out/src/bin/tree.js:38:32)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

bison.grammar

```
@top Grammar {
  "%{"
  Prologue 
  "%}"
  BisonDeclarations
  "%%"
  GrammarRules
  "%%"
  Epilogue
}

Prologue {
  (token | dq_string | sq_string )*
}

BisonDeclarations {
  (token | dq_string | sq_string )*
}

GrammarRules {
  (token | dq_string | sq_string )*
}

Epilogue {
  (token | dq_string | sq_string )*
}

@tokens {
  token { !["'% \n\r\t/] | normal_percent | normal_slash }
  normal_percent { "%" ![%{}]  }
  normal_slash { "/" ![/*] }
  dq_string { '"' dq_char* '"' }
  dq_char { $[\u{20}\u{21}\u{23}-\u{5b}\u{5d}-\u{10ffff}] | "\\" esc }
  sq_string { "'" sq_char "'" }
  sq_char { $[\u{20}-\u{26}\u{28}-\u{5b}\u{5d}-\u{10ffff}] | "\\" esc }
  esc { $["\\bfnrtu] }
  whitespace { $[ \n\r\t] }
  comment { "//" ![\r\n]* }
  blockComment { "/*" (![*] | "*" ![/])* "*/" }
}

@skip { whitespace | comment | blockComment }
```

t.y

```
%{

aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa 

bbb	/* disable the global variable definition */

aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa aa

%}

Bison declarations

%%
Grammar rules
%%

Epilogue
```

**Comment by marijnh** [comment]
This was coincidentally fixed a few hours ago in 3b7d78c0f8fd74d
